### ISSUE TITLE
Join Qiskit ecosystem

### ISSUE THREAD

**Issue by frankharkins** [dakk/caml_qiskit#5]
@dakk thanks for your work in maintaining this. Would you be interested in submitting this project to the Qiskit ecosystem? It'd put your project in front of more users and puts the project on our radar so we know how Qiskit is being used. I know Qlasskit is already a member.

[Link to the submission form](https://github.com/Qiskit/ecosystem/issues/new?assignees=octocat&labels=submission&projects=&template=submission.yml&title=%5BSubmission%5D%3A+).

**Comment by dakk** [comment]
Sure, done!
